/**
 * The colour presets a Super Admin can choose from.
 *
 * GENERATED — edit scripts/gen-themes.mjs and re-run `npm run themes`.
 * The generator refuses to emit a preset whose primary/secondary are too close
 * to gradient apart (ΔL >= 18 or Δhue >= 25 in OKLCH), whose body text falls
 * below 7:1 on its own surface, or whose button label falls below 4.5:1.
 *
 * Each preset is only these eight values. Everything else — surfaces, borders,
 * alpha tints, gradients — is derived from them once in index.css, which is
 * what makes 30 themes cost 30x8 values instead of 30x341 declarations.
 */

/** @typedef {'light' | 'dark'} Scheme */

export const THEMES = [
  {
    id: 'signature-pink',
    name: 'Signature Pink',
    scheme: 'light',
    colors: {
      primary: '#FF2E93',
      primaryDeep: '#E01B77',
      secondary: '#7B1E52',
      accent: '#FF87C2',
      ink: '#0A0A0A',
      neutral: '#373737',
      neutralSoft: '#D6D6D6',
      onPrimary: '#0A0A0A',
    },
  },
  {
    id: 'rose-noir',
    name: 'Rose Noir',
    scheme: 'dark',
    colors: {
      primary: '#FF4FA3',
      primaryDeep: '#E02D86',
      secondary: '#4A0F2E',
      accent: '#FFA8CE',
      ink: '#F5F0F2',
      neutral: '#A8A8A8',
      neutralSoft: '#3A3A3A',
      onPrimary: '#0A0A0A',
    },
  },
  {
    id: 'blush-atelier',
    name: 'Blush Atelier',
    scheme: 'light',
    colors: {
      primary: '#E86A9C',
      primaryDeep: '#C94F80',
      secondary: '#3D2430',
      accent: '#F7C2D6',
      ink: '#241A1E',
      neutral: '#373737',
      neutralSoft: '#D6D6D6',
      onPrimary: '#241A1E',
    },
  },
  {
    id: 'magenta-bloom',
    name: 'Magenta Bloom',
    scheme: 'light',
    colors: {
      primary: '#D6197D',
      primaryDeep: '#B01064',
      secondary: '#4B1440',
      accent: '#F58BC0',
      ink: '#14060F',
      neutral: '#373737',
      neutralSoft: '#D6D6D6',
      onPrimary: '#FFFFFF',
    },
  },
  {
    id: 'fuchsia-silk',
    name: 'Fuchsia Silk',
    scheme: 'light',
    colors: {
      primary: '#F0329B',
      primaryDeep: '#CE1F81',
      secondary: '#5C1B4D',
      accent: '#FFA0D0',
      ink: '#180612',
      neutral: '#373737',
      neutralSoft: '#D6D6D6',
      onPrimary: '#180612',
    },
  },
  {
    id: 'plum-couture',
    name: 'Plum Couture',
    scheme: 'light',
    colors: {
      primary: '#A8317A',
      primaryDeep: '#8A2463',
      secondary: '#2E0F28',
      accent: '#E68CC4',
      ink: '#1C0A18',
      neutral: '#373737',
      neutralSoft: '#D6D6D6',
      onPrimary: '#FFFFFF',
    },
  },
  {
    id: 'cerise-luxe',
    name: 'Cerise Luxe',
    scheme: 'light',
    colors: {
      primary: '#E31C6A',
      primaryDeep: '#C21255',
      secondary: '#45122F',
      accent: '#FF8FB4',
      ink: '#160509',
      neutral: '#373737',
      neutralSoft: '#D6D6D6',
      onPrimary: '#FFFFFF',
    },
  },
  {
    id: 'orchid-haze',
    name: 'Orchid Haze',
    scheme: 'light',
    colors: {
      primary: '#CE6BBD',
      primaryDeep: '#A33C90',
      secondary: '#35204A',
      accent: '#EFA9E0',
      ink: '#1E1226',
      neutral: '#373737',
      neutralSoft: '#D6D6D6',
      onPrimary: '#1E1226',
    },
  },
  {
    id: 'raspberry-ink',
    name: 'Raspberry Ink',
    scheme: 'dark',
    colors: {
      primary: '#FF3D7F',
      primaryDeep: '#DB2463',
      secondary: '#3B0A20',
      accent: '#FF9BBE',
      ink: '#F3EEF0',
      neutral: '#A8A8A8',
      neutralSoft: '#3A3A3A',
      onPrimary: '#0A0A0A',
    },
  },
  {
    id: 'coral-rouge',
    name: 'Coral Rouge',
    scheme: 'light',
    colors: {
      primary: '#FF5C7A',
      primaryDeep: '#E03D5C',
      secondary: '#5E1A2A',
      accent: '#FFB0BF',
      ink: '#1F0A10',
      neutral: '#373737',
      neutralSoft: '#D6D6D6',
      onPrimary: '#1F0A10',
    },
  },
  {
    id: 'sunset-amber',
    name: 'Sunset Amber',
    scheme: 'light',
    colors: {
      primary: '#F97316',
      primaryDeep: '#D65A08',
      secondary: '#7C2D12',
      accent: '#FDBA74',
      ink: '#1C1006',
      neutral: '#373737',
      neutralSoft: '#D6D6D6',
      onPrimary: '#1C1006',
    },
  },
  {
    id: 'golden-hour',
    name: 'Golden Hour',
    scheme: 'light',
    colors: {
      primary: '#E0A312',
      primaryDeep: '#BC860A',
      secondary: '#4A3410',
      accent: '#F6D58A',
      ink: '#1E1806',
      neutral: '#373737',
      neutralSoft: '#D6D6D6',
      onPrimary: '#1E1806',
    },
  },
  {
    id: 'terracotta',
    name: 'Terracotta',
    scheme: 'light',
    colors: {
      primary: '#D4785C',
      primaryDeep: '#A4432A',
      secondary: '#3A1A12',
      accent: '#E9A98F',
      ink: '#1D0F0A',
      neutral: '#373737',
      neutralSoft: '#D6D6D6',
      onPrimary: '#1D0F0A',
    },
  },
  {
    id: 'crimson-velvet',
    name: 'Crimson Velvet',
    scheme: 'dark',
    colors: {
      primary: '#E23B4E',
      primaryDeep: '#C22638',
      secondary: '#3C0A12',
      accent: '#F5949E',
      ink: '#F2EDEE',
      neutral: '#A8A8A8',
      neutralSoft: '#3A3A3A',
      onPrimary: '#0A0A0A',
    },
  },
  {
    id: 'copper-dusk',
    name: 'Copper Dusk',
    scheme: 'light',
    colors: {
      primary: '#B87333',
      primaryDeep: '#9A5C22',
      secondary: '#33200E',
      accent: '#E3B584',
      ink: '#1B1108',
      neutral: '#373737',
      neutralSoft: '#D6D6D6',
      onPrimary: '#1B1108',
    },
  },
  {
    id: 'ocean-deep',
    name: 'Ocean Deep',
    scheme: 'light',
    colors: {
      primary: '#0EA5E9',
      primaryDeep: '#0284C7',
      secondary: '#0C4A6E',
      accent: '#7DD3FC',
      ink: '#06131C',
      neutral: '#373737',
      neutralSoft: '#D6D6D6',
      onPrimary: '#06131C',
    },
  },
  {
    id: 'emerald-atelier',
    name: 'Emerald Atelier',
    scheme: 'light',
    colors: {
      primary: '#10B981',
      primaryDeep: '#059669',
      secondary: '#064E3B',
      accent: '#6EE7B7',
      ink: '#04120C',
      neutral: '#373737',
      neutralSoft: '#D6D6D6',
      onPrimary: '#04120C',
    },
  },
  {
    id: 'royal-indigo',
    name: 'Royal Indigo',
    scheme: 'light',
    colors: {
      primary: '#4F46E5',
      primaryDeep: '#4338CA',
      secondary: '#1E1B4B',
      accent: '#A5B4FC',
      ink: '#0B0A1F',
      neutral: '#373737',
      neutralSoft: '#D6D6D6',
      onPrimary: '#FFFFFF',
    },
  },
  {
    id: 'violet-noir',
    name: 'Violet Noir',
    scheme: 'dark',
    colors: {
      primary: '#A855F7',
      primaryDeep: '#9333EA',
      secondary: '#3B0764',
      accent: '#D8B4FE',
      ink: '#F1ECF5',
      neutral: '#A8A8A8',
      neutralSoft: '#3A3A3A',
      onPrimary: '#0A0A0A',
    },
  },
  {
    id: 'teal-studio',
    name: 'Teal Studio',
    scheme: 'light',
    colors: {
      primary: '#14B8A6',
      primaryDeep: '#0D9488',
      secondary: '#134E4A',
      accent: '#5EEAD4',
      ink: '#04120F',
      neutral: '#373737',
      neutralSoft: '#D6D6D6',
      onPrimary: '#04120F',
    },
  },
  {
    id: 'midnight-sapphire',
    name: 'Midnight Sapphire',
    scheme: 'dark',
    colors: {
      primary: '#3B82F6',
      primaryDeep: '#2563EB',
      secondary: '#152C5B',
      accent: '#93C5FD',
      ink: '#EEF2F8',
      neutral: '#A8A8A8',
      neutralSoft: '#3A3A3A',
      onPrimary: '#0A0A0A',
    },
  },
  {
    id: 'arctic-slate',
    name: 'Arctic Slate',
    scheme: 'light',
    colors: {
      primary: '#64748B',
      primaryDeep: '#475569',
      secondary: '#1E293B',
      accent: '#CBD5E1',
      ink: '#0B1220',
      neutral: '#373737',
      neutralSoft: '#D6D6D6',
      onPrimary: '#FFFFFF',
    },
  },
  {
    id: 'lagoon-mist',
    name: 'Lagoon Mist',
    scheme: 'light',
    colors: {
      primary: '#06B6D4',
      primaryDeep: '#0891B2',
      secondary: '#164E63',
      accent: '#67E8F9',
      ink: '#04141A',
      neutral: '#373737',
      neutralSoft: '#D6D6D6',
      onPrimary: '#04141A',
    },
  },
  {
    id: 'monochrome',
    name: 'Monochrome',
    scheme: 'light',
    colors: {
      primary: '#1F1F1F',
      primaryDeep: '#000000',
      secondary: '#8A8A8A',
      accent: '#D4D4D4',
      ink: '#0A0A0A',
      neutral: '#373737',
      neutralSoft: '#D6D6D6',
      onPrimary: '#FFFFFF',
    },
  },
  {
    id: 'ivory-noir',
    name: 'Ivory Noir',
    scheme: 'light',
    colors: {
      primary: '#2B2B2B',
      primaryDeep: '#111111',
      secondary: '#9C8B7A',
      accent: '#E5DCD1',
      ink: '#141414',
      neutral: '#373737',
      neutralSoft: '#D6D6D6',
      onPrimary: '#FFFFFF',
    },
  },
  {
    id: 'charcoal-gold',
    name: 'Charcoal Gold',
    scheme: 'dark',
    colors: {
      primary: '#D4AF37',
      primaryDeep: '#B8942A',
      secondary: '#2A2A2A',
      accent: '#EBD68A',
      ink: '#F4F1EA',
      neutral: '#A8A8A8',
      neutralSoft: '#3A3A3A',
      onPrimary: '#0A0A0A',
    },
  },
  {
    id: 'espresso',
    name: 'Espresso',
    scheme: 'light',
    colors: {
      primary: '#6F4E37',
      primaryDeep: '#553A28',
      secondary: '#241812',
      accent: '#C9A88C',
      ink: '#170F0A',
      neutral: '#373737',
      neutralSoft: '#D6D6D6',
      onPrimary: '#FFFFFF',
    },
  },
  {
    id: 'sage-linen',
    name: 'Sage Linen',
    scheme: 'light',
    colors: {
      primary: '#7C9070',
      primaryDeep: '#5F7255',
      secondary: '#2C3628',
      accent: '#C3D3B8',
      ink: '#131A10',
      neutral: '#373737',
      neutralSoft: '#D6D6D6',
      onPrimary: '#131A10',
    },
  },
  {
    id: 'graphite-mint',
    name: 'Graphite Mint',
    scheme: 'dark',
    colors: {
      primary: '#4ADE80',
      primaryDeep: '#22C55E',
      secondary: '#1F2937',
      accent: '#BBF7D0',
      ink: '#ECF2EE',
      neutral: '#A8A8A8',
      neutralSoft: '#3A3A3A',
      onPrimary: '#0A0A0A',
    },
  },
  {
    id: 'bordeaux',
    name: 'Bordeaux',
    scheme: 'light',
    colors: {
      primary: '#7B2436',
      primaryDeep: '#5E1927',
      secondary: '#2A0C13',
      accent: '#D08D9C',
      ink: '#1A0509',
      neutral: '#373737',
      neutralSoft: '#D6D6D6',
      onPrimary: '#FFFFFF',
    },
  },
];

export const DEFAULT_THEME_ID = 'signature-pink';

export const THEME_IDS = THEMES.map((t) => t.id);

/** Falls back to the default rather than throwing — an unknown id must never
 *  leave the page unstyled. */
export const getTheme = (id) =>
  THEMES.find((t) => t.id === id) ?? THEMES.find((t) => t.id === DEFAULT_THEME_ID);
